-- fetch all the data from hrdata table => Total 1470 Row
SELECT * FROM HRDATA;

-- find the total employee from hrdata table => 1470
SELECT COUNT(DISTINCT EMP_NO) AS TOTAL_EMPLOYEE FROM HRDATA;
SELECT SUM(EMPLOYEE_COUNT) AS TOTAL_EMPLOYEE FROM HRDATA;

-- find the total employee who are in high school => 170
SELECT SUM(EMPLOYEE_COUNT) AS TOTAL_HIGH_SCHOOL_EMP FROM HRDATA WHERE EDUCATION = 'High School';

-- find the total employee who are in sales department => 446
SELECT SUM(EMPLOYEE_COUNT) AS TOTAL_SALES_DEPARTMENT FROM HRDATA WHERE DEPARTMENT = 'Sales';

-- find the total employee who are in r&d department => 961
SELECT SUM(EMPLOYEE_COUNT) AS TOTAL_R&D_DEPARTMENT FROM HRDATA WHERE DEPARTMENT = 'R&D';

-- find the total employee who are in medical feild => 464
SELECT SUM(EMPLOYEE_COUNT) AS TOTAL_MEDICAL_FEILD_EMPLOYEE FROM HRDATA WHERE EDUCATION_FEILD = 'Medical';

-- find the total attrition count => 237
SELECT COUNT(ATTRITION) AS ATTRITION FROM HRDATA WHERE ATTRITION = 'Yes';

-- find the total attrition count who have doctoral degree => 5
SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes' AND EDUCATION = 'Doctoral Degree';

-- find the total attrition count who are in r&d department => 133
SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes' AND DEPARTMENT = 'R&D';

-- find the total attrition count who are medical student in r&d department => 47
SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes' AND DEPARTMENT = 'R&D' AND EDUCATION_FEILD = 'Medical';

-- find the total attrition count who are medical student in high school and department is r&d => 9
SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes' AND DEPARTMENT = 'R&D' AND EDUCATION = 'High School' AND
EDUCATION_FEILD = 'Medical';

-- find the attrition rate => 16.12%
SELECT ((SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes')/SUM(EMPLOYEE_COUNT)*100)::NUMERIC(10, 2) || ' %' AS ATTRITION_RATE
FROM HRDATA;

-- find the attrition rate for r&d department => 20.63%
SELECT ((SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes' AND DEPARTMENT = 'Sales')/SUM(EMPLOYEE_COUNT)*100)::NUMERIC(10, 2) || ' %'
FROM HRDATA WHERE DEPARTMENT = 'Sales';

-- find the active employee => 1233
SELECT SUM(EMPLOYEE_COUNT)-(SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes') AS ACTIVE_EMMPLOYEE
FROM HRDATA;

-- find the active employee of male => 732
SELECT SUM(EMPLOYEE_COUNT)-(SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes' AND GENDER = 'Male')
FROM HRDATA WHERE GENDER = 'Male';

-- find the average age of hrdata => 37
SELECT ROUND(AVG(AGE)) AS AVERAGE_AGE FROM HRDATA;

-- find the attrition count based on gender => 87, 150
SELECT GENDER, COUNT(ATTRITION) AS ATTRITION,
((CAST(COUNT(ATTRITION) AS FLOAT)/CAST((SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes') AS FLOAT))*100)::NUMERIC(10, 2) || ' %' AS ATTRITION_PCT
FROM HRDATA
WHERE ATTRITION = 'Yes'
GROUP BY GENDER;

-- find the attrition count based on gender for high school => 11, 20
SELECT GENDER, COUNT(ATTRITION)
FROM HRDATA
WHERE ATTRITION = 'Yes' AND EDUCATION = 'High School'
GROUP BY GENDER;

-- find number of employee by age group and gender
SELECT AGE_BAND, GENDER, SUM(EMPLOYEE_COUNT) AS TOTAL_EMPLOYEE
FROM HRDATA
GROUP BY AGE_BAND, GENDER
ORDER BY AGE_BAND;

-- find the attrition count and percentage based on department => 12, 92, 133
SELECT DEPARTMENT, COUNT(ATTRITION) AS ATTRITION, 
((CAST(COUNT(ATTRITION) AS FLOAT)/CAST((SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes') AS FLOAT))*100)::NUMERIC(10, 2) || ' %' AS ATTRITION_PCT
FROM HRDATA
WHERE ATTRITION = 'Yes'
GROUP BY DEPARTMENT;

-- find the attrition count and percentage based on department for female => 6, 38, 43
SELECT DEPARTMENT, COUNT(ATTRITION), 
ROUND(((CAST(COUNT(ATTRITION) AS NUMERIC)/(SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes' AND GENDER = 'Female'))*100), 2) || ' %'
FROM HRDATA
WHERE ATTRITION = 'Yes' AND GENDER = 'Female'
GROUP BY DEPARTMENT;

-- find the total employee based on age => Total 43 Row
SELECT AGE, SUM(EMPLOYEE_COUNT) AS TOTAL_EMPLOYEE
FROM HRDATA
GROUP BY AGE
ORDER BY AGE;

-- find the total employee based on age => Total 43 Row
SELECT AGE, SUM(EMPLOYEE_COUNT)
FROM HRDATA
WHERE DEPARTMENT = 'R&D'
GROUP BY AGE
ORDER BY AGE

-- find total attrition based on educaton feild => Total 6 Row
SELECT EDUCATION_FEILD, COUNT(ATTRITION) AS TOTAL_ATTRITION
FROM HRDATA
WHERE ATTRITION = 'Yes'
GROUP BY EDUCATION_FEILD
ORDER BY TOTAL_ATTRITION DESC;

-- find total attrition for sales department based on educaton feild => Total 5 Row
SELECT EDUCATION_FEILD, COUNT(ATTRITION)
FROM HRDATA
WHERE ATTRITION = 'Yes' AND DEPARTMENT = 'Sales'
GROUP BY EDUCATION_FEILD;

-- find total attrition and attrition percentage based on age group and gender => Total 10 Row
SELECT AGE_BAND, GENDER, COUNT(ATTRITION) AS TOTAL_ATTRITION, 
ROUND((CAST(COUNT(ATTRITION) AS NUMERIC)/(SELECT COUNT(ATTRITION) FROM HRDATA WHERE ATTRITION = 'Yes'))*100, 2) || ' %' AS ATTRITION_PCT
FROM HRDATA
WHERE ATTRITION = 'Yes'
GROUP BY AGE_BAND, GENDER
ORDER BY AGE_BAND, GENDER;


-- find the job role and satisfiction rating for each employee => Total 9 Row
SELECT DISTINCT JOB_SATISFICTION FROM HRDATA;

CREATE EXTENSION IF NOT EXISTS TABLEFUNC;

SELECT *
FROM CROSSTAB(
	'SELECT JOB_ROLE, JOB_SATISFICTION, SUM(EMPLOYEE_COUNT)
	FROM HRDATA
	GROUP BY JOB_ROLE, JOB_SATISFICTION
	ORDER BY JOB_ROLE, JOB_SATISFICTION'
) AS CT(JOB_ROLE VARCHAR(50), ONE NUMERIC, TWO NUMERIC, THREE NUMERIC, FOUR NUMERIC)
ORDER BY JOB_ROLE;


SELECT AGE_BAND, GENDER, SUM(EMPLOYEE_COUNT)
FROM HRDATA
GROUP BY AGE_BAND, GENDER
ORDER BY AGE_BAND, GENDER;
