CREATE TABLE HRDATA
(
	EMP_NO INT8 PRIMARY KEY,
	GENDER VARCHAR(50) NOT NULL,
	MARITAL_STATUS VARCHAR(50),
	AGE_BAND VARCHAR(50),
	AGE INT8,
	DEPARTMENT VARCHAR(50),
	EDUCATION VARCHAR(50),
	EDUCATION_FEILD VARCHAR(50),
	JOB_ROLE VARCHAR(50),
	BUSINESS_TRAVEL VARCHAR(50),
	EMPLOYEE_COUNT INT8,
	ATTRITION VARCHAR(50),
	ATTRITION_LABEL VARCHAR(50),
	JOB_SATISFICTION INT8,
	ACTIVE_EMPLOYEE INT8
);

SELECT * FROM HRDATA;

COPY HRDATA FROM 'J:\Portfolio Project\HR Dashboard\data\hrdata.csv' DELIMITER ',' CSV HEADER;

SELECT * FROM HRDATA;
